config:
  vcam:
    trim_y: 300
    trim_x: 400
    frame_id: camera
  prepro:
    capture_frame_id: camera/capture0
  vrobo:
    target_frame_id: tool0_controller
  report:
    keys: ["__recipe__", "retry", "pcount","fitness","rmse","azimuth","rotation","fitness_sub","rmse_sub","azimuth_sub","rotation_sub","tcap","tfeat","tmatch","tsolve"]
    labels: ["レシピ", "解析回数", "点数","一致度","平均誤差","傾き[deg]","回転[deg]","位相 一致度","位相 平均誤差","位相 傾き[deg]","位相 回転[deg]","撮影処理時間[sec]","特徴処理時間[sec]","マッチング処理時間[sec]","解析処理時間[sec]"]
  post0:
    proc: 0
    solver: "evaluate_solver"
    scenes: ["surface_sub"]
    scene_frame_ids: ["camera/capture0"]
    master_frame_ids: ["camera/master0_sub"]
    solve_frame_id: "camera/capture0"
  vscene:
    model_frame_ids: [marud1, marud2, marud3, circle1, circle2, circle3]
  autoseq:
    base_frame_id: "base"
    source_frame_id: "camera/master0"
    target_frame_id: "camera/capture0/solve0"

vrobo:
  xyz: [0,0,0]
  rpy: [0,0,0]
  path_interval:
    ip: rot_z
    xyz: [-100,0,600]
    rpy: [0,120,0]
    var: [0,360]
    pitch: 3.6
    pause: 0.1
  path_point:
    ip: rot_z
    xyz: [-500,0,1000]
    rpy: [0,180,90]
    var: [90]
    pause: 1
  uf: uf0

vscene:
  marud1:
    name: marud
    show: true
    ini_z: 0
    uf: uf1
    xyz: [0,0,0]
    rpy: [0,0,0]
  marud2:
    name: marud
    show: false
    ini_z: 400
    uf: uf1
    xyz: [0,0,0]
    rpy: [0,0,0]
  marud3:
    name: marud
    show: false
    ini_z: 800
    uf: uf1
    xyz: [0,0,0]
    rpy: [0,0,0]
  circle1:
    name: circle
    show: true
    ini_z: 0
    uf: uf2
    xyz: [0,0,0]
    rpy: [0,0,0]
  circle2:
    name: circle
    show: true
    ini_z: 200
    uf: uf2
    xyz: [0,0,0]
    rpy: [0,0,0]
  circle3:
    name: circle
    show: true
    ini_z: 400
    uf: uf2
    xyz: [0,0,0]
    rpy: [0,0,0]
  
picker:
  fitness:
    min: 0
  azimuth:
    max: 0

config_tf:
  base:
    parent_frame_id: world  #In stead of URDF
  flange:
    parent_frame_id: tool0_controller
  marud1:
    parent_frame_id: world
    transform:
      rotation:
        w: 1
        x: 0
        y: 0
        z: 0
      translation:
        x: 800
        y: 700
        z: 0
  marud2:
    parent_frame_id: world
    transform:
      rotation:
        w: 1
        x: 0
        y: 0
        z: 0
      translation:
        x: 800
        y: 700
        z: 0
  marud3:
    parent_frame_id: world
    transform:
      rotation:
        w: 1
        x: 0
        y: 0
        z: 0
      translation:
        x: 800
        y: 700
        z: 0
  circle1:
    parent_frame_id: world
    transform:
      rotation:
        w: 1
        x: 0
        y: 0
        z: 0
      translation:
        x: 800
        y: -700
        z: 0
  circle2:
    parent_frame_id: world
    transform:
      rotation:
        w: 1
        x: 0
        y: 0
        z: 0
      translation:
        x: 800
        y: -700
        z: 0
  circle3:
    parent_frame_id: world
    transform:
      rotation:
        w: 1
        x: 0
        y: 0
        z: 0
      translation:
        x: 800
        y: -700
        z: 0
  camera:
    transform:
      rotation:
        w: 1
        x: 0
        y: 0
        z: 0
      translation:
        x: 0
        y: 0
        z: 0
  uf0:
    parent_frame_id: base
  uf1:                       #marudo
    parent_frame_id: base
    transform:
      rotation:
        w: 1
        x: 0
        y: 0
        z: 0
      translation:
        x: 800
        y: 700
        z: 0
  uf2:                       #cirle
    parent_frame_id: base
    transform:
      rotation:
        w: 1
        x: 0
        y: 0
        z: 0
      translation:
        x: 800
        y: -700
        z: 0
  uf9:                       #as VT
    parent_frame_id: base

post0:
  evaluate: Off
