autoseq:
  campos:
    pos0:
      path:
        ip: rot_z
        pitch: 36
        rpy:
        - 0
        - 180
        - 90
        var:
        - 0
        - 360
        xyz:
        - -500
        - 0
        - 1100
      pos: 0
      type: path_interval
      uf: uf1
cropper:
  cropR: 0
  cropR2: 0.08
  cropZ: 0
  ladC: 0
  ladW: 0
  ladW2: 30000
  mesh: 0
  nfmin: 0
  nfrad: 5
picker:
  azimuth:
    max: 20
    min: 0
  fitness:
    max: 1
    min: 0.65
  rmse:
    max: 5
    min: 0
  rotation:
    max: 180
    min: -180
  transX:
    max: 3000
    min: -3000
  transY:
    max: 3000
    min: -3000
post:
  axis_save: true
  evaluate: false
rovi:
  pshift_genpc:
    calc:
      bw_diff: 8
      darkness: 5
  ycam:
    ExposureTimeLevel: 4
    camera:
      Gain: 80
    hdr:
      enabled: false
      pcgen_publish: false
      projector:
        Intensity: 0.2
    projector:
      Intensity: 255
searcher:
  cutter:
    base: 0
    offset: 0
    width: 0
  distance_threshold: 9
  feature_mesh: 6
  feature_radius: 30
  icp_threshold: 3
  normal_min_nn: 5
  normal_radius: 12
  repeat: 3
  rotate: 0
